In [1]:
import pandas as pd

## 데이터 컬럼 수정

#### 보안등 데이터 수정

In [3]:
light = pd.read_csv("./data/스마트치안빅데이터플랫폼_서울시 보안등 데이터_20221107.csv")

# 보안등 데이터 -> 컬럼 인덱스 추가
light.columns = ["번호", "보안등위치명", "설치개수", "소재지도로명주소", "소재지지번주소", "위도", "경도", "설치년도", "설치형태", "관리기관전화번호", "관리기관명",\
                "데이터기준일자", "경찰서명", "경찰서부서명", "경찰서부서코드", "시도경찰청명"]

In [48]:
light.to_csv("./data_modify/light.csv")

#### cctv 데이터 수정

In [10]:
cctv = pd.read_csv("./data/스마트치안빅데이터플랫폼_서울시 CCTV 데이터20221107.csv")
cctv.columns = ["번호", "자치구명", "안심주소", "CCTV용도", "위도", "경도", "CCTV수량", "수정일시", "경찰서명", "경찰서부서명", "경찰서부서코드", "시도경찰청명"]

In [12]:
cctv.to_csv("./data_modify/cctv.csv")

#### 체감안전 데이터 수정

In [27]:
safe = pd.read_csv("./data/스마트치안빅데이터플랫폼_지역별 체감안전(행정동).csv")
safe = safe[safe["충청북도"]=="서울특별시"]
safe

,2018,충청북도,충주시,대소원면,충주,103584.0000000,6215,86,8,2146,...,3156,403,283,583,3.1,714,290,0.3,0.4,0.5
31,2018,서울특별시,용산구,용문동,서울용산,54808.0,10017,331,16,2284,...,3637,447,882,3253,68,2172,424,0,0,0
32,2018,서울특별시,성동구,왕십리제2동,서울성동,17748.0,8129,126,14,1831,...,2897,354,647,1914,22,1750,256,0,0,0
33,2018,서울특별시,성동구,금호1가동,서울성동,16087.0,8129,126,14,1831,...,2897,354,647,1914,22,1750,256,0,0,0
34,2018,서울특별시,성동구,성수2가제1동,서울성동,17580.0,8129,126,14,1831,...,2897,354,647,1914,22,1750,256,0,0,0
35,2018,서울특별시,광진구,중곡제3동,서울광진,17604.0,10768,229,15,2097,...,3962,422,866,3819,55,2122,406,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3106,2018,서울특별시,강동구,성내제3동,서울강동,23896.0,10436,170,22,1993,...,4634,476,770,3497,48,2146,545,0,0,0
3107,2018,서울특별시,강동구,둔촌제1동,서울강동,301.0,10436,170,22,1993,...,4634,476,770,3497,48,2146,545,0,0,0
3130,2018,서울특별시,중구,필동,서울중부,44033.0,6214,132,16,940,...,3032,296,336,868,7,1255,186,0,0,0
3131,2018,서울특별시,중구,황학동,서울중부,12373.0,6214,132,16,940,...,3032,296,336,868,7,1255,186,0,0,0
3132,2018,서울특별시,중구,동화동,서울중부,11043.0,6214,132,16,940,...,3032,296,336,868,7,1255,186,0,0,0

In [39]:
col_name = pd.read_csv("./data/체감안전_컬럼정의서.csv", encoding='cp949')
col_list = list(col_name.iloc[:,2])
col_list

['기준년도',
 '시도',
 '시군구',
 '행정동',
 '경찰서명',
 '인구',
 '합계원표',
 '성범죄원표',
 '살인강도원표',
 '교통범죄원표',
 '절도범죄원표',
 '폭력범죄원표',
 '지능경제범죄원표',
 '기타원표',
 '합계112',
 '성범죄112',
 '성범죄성폭력112',
 '성범죄데이트폭력112',
 '성범죄스토킹112',
 '살인강도112',
 '살인강도살인112',
 '살인강도강도마약112',
 '교통범죄112',
 '교통범죄교통사고112',
 '교통범죄교통불편112',
 '교통범죄교통위반112',
 '교통범죄사망대형사고112',
 '교통범죄인피도주112',
 '교통범죄음주운전112',
 '절도범죄112',
 '절도범죄절도112',
 '절도범죄소매치기112',
 '지능경제범죄112',
 '지능경제범죄사기112',
 '지능경제범죄보이스피싱112',
 '폭력112',
 '폭력가정폭력112',
 '폭력아동학대가정내112',
 '폭력아동학대기타112',
 '폭력납치감금112',
 '폭력폭력112',
 '폭력공갈112',
 '폭력협박112',
 '폭력재물손괴112',
 '폭력학교폭력112',
 '폭력청소년비행112',
 '기타112',
 '기타도박112',
 '기타주거침입112',
 '기타풍속영업112',
 '기타수배불심자112',
 '기타기타형사범112',
 '기타시비112',
 '기타행패소란112',
 '기타무전취식승차112',
 '기타무취자112',
 '기타보호조치112',
 '기타위험방지112',
 '기타기타경범112',
 '기타상담문의112',
 '기타변사자112',
 '기타비상벨112',
 '기타경비업체요청112',
 '기타가출112',
 '기타분실습득112',
 '기타FTX112',
 '기타자살112',
 '기타실종112',
 '기타내용확인불가112',
 '기타화재112',
 '기타구조요청112',
 '기타소음112',
 '기타노점상112',
 '기타기타타기관112',
 '기타서비스요청112',
 '기타청탁금지법112',
 '기타재해재난112',
 '기타기타위험동물112']

In [40]:
safe.columns = col_list

In [42]:
safe.to_csv("./data_modify/safe.csv")

#### 경찰서 데이터 수정

In [46]:
police = pd.read_csv("./data/공공데이터포털_경찰청_경찰관서 위치 주소 현황_20230811.csv", encoding='cp949')
police = police[police["시도청"]=="서울청"]
police

      연번  시도청   경찰서 관서명   구분          전화번호                              주소
0      1  서울청  서울중부  을지  지구대  02-2279-1908               서울특별시 중구  을지로 234
1      2  서울청  서울중부  광희  지구대  02-2233-1444             서울특별시 중구  퇴계로 375-1
2      3  서울청  서울중부  약수  지구대  02-2234-8112      서울특별시 중구  동호로 5길 15, 약수지구대
3      4  서울청  서울중부  신당  파출소  02-2252-0435  서울특별시 중구  다산로 248 (신당동, 신당파출소)
4      5  서울청  서울중부  장충  파출소  02-2274-9003               서울특별시 중구  동호로 261
..   ...  ...   ...  ..  ...           ...                             ...
238  239  서울청  서울수서  대치  지구대   02-538-1312              서울특별시 강남구  삼성로 203
239  240  서울청  서울수서  수서  파출소   02-445-0112            서울특별시 강남구  밤고개로1길 48
240  241  서울청  서울수서  대왕  파출소  02-3411-0323              서울특별시 강남구  헌릉로 623
241  242  서울청  서울수서  일원  지구대  02-3411-0112       서울특별시 강남구  일원로3길 35 일원파출소
242  243  서울청  서울수서  개포  지구대   02-571-0112        서울특별시 강남구  개포로 261(1268)

[243 rows x 7 columns]

In [47]:
police.to_csv("./data_modify/police.csv")

## 범죄현황 데이터 전처리

In [3]:
crime = pd.read_csv("./data/서울시_범죄발생현황.csv")
crime

,자치구별(1),자치구별(2),2022,2022.1,2022.2,2022.3,2022.4,2022.5,2022.6,2022.7,2022.8,2022.9,2022.10,2022.11
0,자치구별(1),자치구별(2),합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계
1,자치구별(1),자치구별(2),소계,소계,살인,살인,강도,강도,강간·강제추행,강간·강제추행,절도,절도,폭력,폭력
2,자치구별(1),자치구별(2),발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
3,합계,소계,90399,65097,104,98,117,112,5816,5344,37579,20205,46783,39338
4,합계,종로구,3138,3284,2,3,8,8,228,988,1313,932,1587,1353
5,합계,중구,3071,2119,1,2,5,4,194,123,1365,724,1506,1266
6,합계,용산구,2967,2093,5,3,7,7,280,238,978,508,1697,1337
7,합계,성동구,2194,1597,2,2,2,2,125,97,979,538,1086,958
8,합계,광진구,3619,2498,6,5,-,-,230,174,1670,831,1713,1488
9,합계,동대문구,3253,2231,4,4,2,2,125,106,1556,823,1566,1296
10,합계,중랑구,3599,2671,2,2,2,2,150,121,1508,882,1937,1664
11,합계,성북구,2749,2125,3,3,1,1,158,129,1143,715,1444,1277
12,합계,강북구,2832,2343,5,4,5,6,177,147,872,589,1773,1597
13,합계,도봉구,2141,1569,3,3,-,-,70,54,969,546,1099,966
14,합계,노원구,3896,2641,3,3,3,1,180,151,1504,729,2206,1757
15,합계,은평구,3487,2658,4,4,5,4,176,146,1497,946,1805,1558
16,합계,서대문구,2374,1605,5,4,6,6,157,144,1114,565,1092,886
17,합계,마포구,4096,2814,2,2,2,1,436,368,1451,653,2205,1790
18,합계,양천구,3169,2130,2,2,3,3,114,92,1474,781,1576,1252
19,합계,강서구,4663,3591,3,3,7,7,261,195,1991,1185,2401,2201
20,합계,구로구,3857,2732,11,11,8,9,217,145,1565,841,2056,1726
21,합계,금천구,2577,1887,2,1,3,3,127,87,1118,662,1327,1134
22,합계,영등포구,4819,3186,5,6,10,9,327,237,2062,953,2415,1981
23,합계,동작구,2735,1741,2,3,5,5,212,107,1195,588,1321,1038
24,합계,관악구,4879,3411,10,8,9,8,327,279,1966,1050,2567,2066
25,합계,서초구,4459,3098,3,2,3,3,431,328,1921,1024,2101,1741
26,합계,강남구,6947,5020,12,10,11,10,667,534,2495,1207,3762,3259
27,합계,송파구,5167,3409,2,2,5,6,290,220,2201,1033,2669,2148
28,합계,강동구,3711,2644,5,6,5,5,157,134,1672,900,1872,1599

In [5]:
crime = crime.drop(["자치구별(1)"], axis=1)

In [10]:
crime = crime.rename(mapper={"자치구별(2)": "county_name", "2022": "total_crime", "2022.1": "total_arrest", 
                     "2022.2": "murder_crime", "2022.3": "murder_arrest",
                     "2022.4": "robbery_crime", "2022.5": "robbery_arrest", 
                     "2022.6": "sex_crime", "2022.7": "sex_arrest",
                     "2022.8": "theft_crime", "2022.9": "theft_arrest",
                     "2022.10": "violence_crime", "2022.11": "violence_arrest"}, axis=1)
crime

,county_name,total_crime,total_arrest,murder_crime,murder_arrest,robbery_crime,robbery_arrest,sex_crime,sex_arrest,theft_crime,theft_arrest,violence_crime,violence_arrest
0,자치구별(2),합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계
1,자치구별(2),소계,소계,살인,살인,강도,강도,강간·강제추행,강간·강제추행,절도,절도,폭력,폭력
2,자치구별(2),발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
3,소계,90399,65097,104,98,117,112,5816,5344,37579,20205,46783,39338
4,종로구,3138,3284,2,3,8,8,228,988,1313,932,1587,1353
5,중구,3071,2119,1,2,5,4,194,123,1365,724,1506,1266
6,용산구,2967,2093,5,3,7,7,280,238,978,508,1697,1337
7,성동구,2194,1597,2,2,2,2,125,97,979,538,1086,958
8,광진구,3619,2498,6,5,-,-,230,174,1670,831,1713,1488
9,동대문구,3253,2231,4,4,2,2,125,106,1556,823,1566,1296
10,중랑구,3599,2671,2,2,2,2,150,121,1508,882,1937,1664
11,성북구,2749,2125,3,3,1,1,158,129,1143,715,1444,1277
12,강북구,2832,2343,5,4,5,6,177,147,872,589,1773,1597
13,도봉구,2141,1569,3,3,-,-,70,54,969,546,1099,966
14,노원구,3896,2641,3,3,3,1,180,151,1504,729,2206,1757
15,은평구,3487,2658,4,4,5,4,176,146,1497,946,1805,1558
16,서대문구,2374,1605,5,4,6,6,157,144,1114,565,1092,886
17,마포구,4096,2814,2,2,2,1,436,368,1451,653,2205,1790
18,양천구,3169,2130,2,2,3,3,114,92,1474,781,1576,1252
19,강서구,4663,3591,3,3,7,7,261,195,1991,1185,2401,2201
20,구로구,3857,2732,11,11,8,9,217,145,1565,841,2056,1726
21,금천구,2577,1887,2,1,3,3,127,87,1118,662,1327,1134
22,영등포구,4819,3186,5,6,10,9,327,237,2062,953,2415,1981
23,동작구,2735,1741,2,3,5,5,212,107,1195,588,1321,1038
24,관악구,4879,3411,10,8,9,8,327,279,1966,1050,2567,2066
25,서초구,4459,3098,3,2,3,3,431,328,1921,1024,2101,1741
26,강남구,6947,5020,12,10,11,10,667,534,2495,1207,3762,3259
27,송파구,5167,3409,2,2,5,6,290,220,2201,1033,2669,2148
28,강동구,3711,2644,5,6,5,5,157,134,1672,900,1872,1599

In [11]:
crime.head(7)

,county_name,total_crime,total_arrest,murder_crime,murder_arrest,robbery_crime,robbery_arrest,sex_crime,sex_arrest,theft_crime,theft_arrest,violence_crime,violence_arrest
0,자치구별(2),합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계
1,자치구별(2),소계,소계,살인,살인,강도,강도,강간·강제추행,강간·강제추행,절도,절도,폭력,폭력
2,자치구별(2),발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
3,소계,90399,65097,104,98,117,112,5816,5344,37579,20205,46783,39338
4,종로구,3138,3284,2,3,8,8,228,988,1313,932,1587,1353
5,중구,3071,2119,1,2,5,4,194,123,1365,724,1506,1266
6,용산구,2967,2093,5,3,7,7,280,238,978,508,1697,1337

In [14]:
crime = crime.iloc[4:, :]

In [18]:
crime = crime.reset_index()

In [20]:
crime = crime.drop(["index"], axis=1)

In [24]:
crime.columns

Index(['county_name', 'total_crime', 'total_arrest', 'murder_crime',
       'murder_arrest', 'robbery_crime', 'robbery_arrest', 'sex_crime',
       'sex_arrest', 'theft_crime', 'theft_arrest', 'violence_crime',
       'violence_arrest', 'city_name'],
      dtype='object')

In [26]:
crime["city_name"] = "서울"
crime = crime[["city_name", "county_name", 'total_crime', 'total_arrest', 'murder_crime',
       'murder_arrest', 'robbery_crime', 'robbery_arrest', 'sex_crime',
       'sex_arrest', 'theft_crime', 'theft_arrest', 'violence_crime',
       'violence_arrest']]

In [28]:
crime.to_csv("./data3/crime.csv", index=False)